/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-02-24 05:40:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class genre_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <!--기본 틀-->\r\n");
      out.write("    <style>\r\n");
      out.write("        .genreCheck {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    } \r\n");
      out.write("    .article input {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("    .article > label:nth-of-type(2) text {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        bottom: 140px;\r\n");
      out.write("        height: 180px;\r\n");
      out.write("        background-color: beige;\r\n");
      out.write("    }\r\n");
      out.write("    .article button {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top: 25px;\r\n");
      out.write("        left: 35px;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tumb{\r\n");
      out.write("        width: 10px !important;\r\n");
      out.write("        height: 10px !important;\r\n");
      out.write("        margin: 0 !important;\r\n");
      out.write("        padding: 0 !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script> \r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link href=\"/app/resources/css/content.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"/app/resources/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/app/resources/images/thumb.png\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"들어오지 마셈\" />\r\n");
      out.write("    <meta property=\"og:description\" content=\"뭐보지? 하믄 들어와\" />\r\n");
      out.write("    <meta property=\"og:image\" content=\"/app/resources/images/thumb.png\" }\" />\r\n");
      out.write("    <title>ㅇㅌㅊㅊ</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body><!--\r\n");
      out.write("    <header class=\"head\" id=\"header\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <h1><a href=\"./main.html\">ㅇㅌㅊㅊ!</a></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search\">\r\n");
      out.write("            <select>\r\n");
      out.write("                <option>네이버</option>\r\n");
      out.write("                <option>탑툰</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\" id=\"main_serach\"> <button>검색하기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"login\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"./login.html\">로그인</a>></li>\r\n");
      out.write("                <li><a href=\"./signin.html\">회원가입</a>></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <menu>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"./top.html\"> T O P </a></li>\r\n");
      out.write("                <li><a href=\"./today.html\"> 오 늘 의  추 천 </a></li>\r\n");
      out.write("                <li><a href=\"./genre.html\"> 장 르 </a></li>\r\n");
      out.write("                <li><a href=\"./bbs.html\"> 자 유  게 시 판 </a></li>  \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </menu>  --><!-- 드라마 학원 액션 옴니버스 판타지 공포/스릴러/미스터리 개그 일상 순정/감성/로맨스 스포츠 BL+백합 -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"genreCheck\">\r\n");
      out.write("        <form action=\"\" method=\"post\" id=\"form\">\r\n");
      out.write("        <input type=\"checkbox\" id=\"drama\" name=\"drama\">드라마\r\n");
      out.write("        <input type=\"checkbox\" id=\"school\" name=\"school\">학원\r\n");
      out.write("        <input type=\"checkbox\" id=\"action\" name=\"action\">액션\r\n");
      out.write("        <input type=\"checkbox\" id=\"omnibus\" name=\"omnibus\">옴니버스\r\n");
      out.write("        <input type=\"checkbox\" id=\"fantasi\" name=\"fantasi\">판타지\r\n");
      out.write("        <input type=\"checkbox\" id=\"scary\" name=\"scary\">공포/스릴러/미스터리\r\n");
      out.write("        <input type=\"checkbox\" id=\"gag\" name=\"gag\">개그\r\n");
      out.write("        <input type=\"checkbox\" id=\"life\" name=\"life\">일상\r\n");
      out.write("        <input type=\"checkbox\" id=\"romance\" name=\"romance\">로맨스/순정/감성\r\n");
      out.write("        <input type=\"checkbox\" id=\"sport\" name=\"sport\">스포츠\r\n");
      out.write("        <input type=\"checkbox\" id=\"gay\" name=\"gay\">BL+백합\r\n");
      out.write("       <!--  <input type=\"submit\" id=\"submit\" value=\"적용\"> 원형-->\r\n");
      out.write("       <input type=\"button\" id=\"submit\" value=\"적용\">\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"article\">\r\n");
      out.write("            <p>퀘스트 지상주의</p>\r\n");
      out.write("            <a href=\"https://comic.naver.com/webtoon/list?titleId=783052\"><img src=\"/app/resources/images/n-783052.jpg\"></a>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"firstButton(id)\"  id=\"n-783052-f\">\r\n");
      out.write("                <text>미션을 깨면 카드를 준다? 심지어 훔쳐보기 까지!?</text></label>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"secondButton(id)\"  id=\"n-783052-s\">\r\n");
      out.write("                <text>여유공간\r\n");
      out.write("                    <button onClick=\"location.href='#'\">댓글 더보기</button>\r\n");
      out.write("                </text></label></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"article\">\r\n");
      out.write("            <p>쇼미더 럭키짱!</p>\r\n");
      out.write("            <a href=\"https://comic.naver.com/webtoon/list?titleId=783054\"><img src=\"/app/resources/images/n-783054.jpg\"></a>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"firstButton(id)\"  id=\"n-783054-f\">\r\n");
      out.write("                <text>김성모가 박태준이랑 같이 연재를 했다? 이거 대작일지도..?</text></label>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"secondButton(id)\"  id=\"n-783054-s\">\r\n");
      out.write("                <text>여유공간\r\n");
      out.write("                    <button onClick=\"location.href='#'\">댓글 더보기</button>\r\n");
      out.write("                </text></label></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"article\">\r\n");
      out.write("            <p>평범한 8반</p>\r\n");
      out.write("            <a href=\"https://comic.naver.com/webtoon/list?titleId=597478\"><img src=\"/app/resources/images/n-597478.jpg\"></a>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"firstButton(id)\"  id=\"n-597478-f\">\r\n");
      out.write("                <text>왕뚝배기 동원이 머리 언제 작아졌음?</text></label>                          \r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"secondButton(id)\"  id=\"n-597478-s\">\r\n");
      out.write("                <text>사이트 주인이 만든 글귀\r\n");
      out.write("                    <button onClick=\"location.href='#'\">댓글 더보기</button>\r\n");
      out.write("                </text></label></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"article\">\r\n");
      out.write("            <p>신의 탑</p>\r\n");
      out.write("            <a href=\"https://comic.naver.com/webtoon/list?titleId=183559\"><img src=\"/app/resources/images/n-183559.jpg\"></a>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"firstButton(id)\"  id=\"n-183559-f\">\r\n");
      out.write("                <text>도대체 이 신의탑은 언제 끝나냐 원피스 보다 오래갈듯.</text></label>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"secondButton(id)\"  id=\"n-183559-s\">\r\n");
      out.write("                <text>사이트 주인이 만든 글귀\r\n");
      out.write("                    <button onClick=\"location.href='#'\">댓글 더보기</button>\r\n");
      out.write("                </text></label></div>\r\n");
      out.write("        <div class=\"article\">\r\n");
      out.write("            <p>제목</p>\r\n");
      out.write("            <a href=\"#\"><img src=\"\" alt=\"썸네일\" style=\"height: 100px;\"></a>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"firstButton(id)\"  id=\"M-AN-f\">\r\n");
      out.write("                <text>해당 웹툰에 대한 설명? 내용</text></label>\r\n");
      out.write("            <label><input type=\"checkbox\" onclick=\"secondButton(id)\"  id=\"M-AN-s\">\r\n");
      out.write("                <text>1.한번쯤은 보는걸 추천합니다.\r\n");
      out.write("                    <br><span>추천30개</span> <img src=\"/app/resources/images/n-1234.png\" class=\"tumb\">\r\n");
      out.write("                    <br>\r\n");
      out.write("                    2.개인적으로 최예작입니다 추천합니다.\r\n");
      out.write("                    <br><span>추천26개</span> <img src=\"/app/resources/images/n-1234.png\" class=\"tumb\">\r\n");
      out.write("                    <br>\r\n");
      out.write("                    3.안경 벗고 추천합니다.\r\n");
      out.write("                    <br><span>추천25개</span> <img src=\"/app/resources/images/n-1234.png\" class=\"tumb\">\r\n");
      out.write("                    <button onClick=\"location.href='./commentbbs'\">댓글 더보기</button>\r\n");
      out.write("                    \r\n");
      out.write("                </text></label></div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 장르 script -->\r\n");
      out.write("    <script>\r\n");
      out.write("        function firstButton(article){\r\n");
      out.write("            console.log(article);\r\n");
      out.write("            const first =document.getElementById(article).nextElementSibling;\r\n");
      out.write("            const second =document.getElementById(article).parentElement.nextElementSibling.lastElementChild;\r\n");
      out.write("            console.log(first);\r\n");
      out.write("            console.log(second);\r\n");
      out.write("            first.style.display=\"none\";\r\n");
      out.write("            second.style.display='inline-block';    \r\n");
      out.write("        }\r\n");
      out.write("        function secondButton(article){\r\n");
      out.write("            console.log(article)\r\n");
      out.write("            const first =document.getElementById(article).nextElementSibling;\r\n");
      out.write("            const second =document.getElementById(article).parentElement.previousElementSibling.lastElementChild;\r\n");
      out.write("            console.log(first);\r\n");
      out.write("            console.log(second);\r\n");
      out.write("            first.style.display=\"none\";\r\n");
      out.write("            second.style.display='inline-block';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>/*\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		$(\"#submit\").on(\"click\",function(){\r\n");
      out.write("			alert(\"A\");\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				\r\n");
      out.write("				type : \"GET\",\r\n");
      out.write("				async : true,\r\n");
      out.write("				dataType : \"json\",\r\n");
      out.write("				url:\"/app/genre2?p1=on&p2=on\",\r\n");
      out.write("				\"Content-Type\": \"application/json\",\r\n");
      out.write("//	 			data{}에서는 EL을 \"\"로 감싸야함..그외에는 그냥 사용\r\n");
      out.write("\r\n");
      out.write("	 			beforeSend : function(){\r\n");
      out.write("	 				alert(\"시작전\");\r\n");
      out.write("	 			},\r\n");
      out.write("	 			complete: function(){\r\n");
      out.write("	 				alert(\"완료후\");\r\n");
      out.write("	 			},	 	 			\r\n");
      out.write("				success:function(data){	\r\n");
      out.write("					alert(data);\r\n");
      out.write("					showHtml(data);		\r\n");
      out.write("				},\r\n");
      out.write("				error : function(xhr){\r\n");
      out.write("					alert(\"error html = \" + xhr.statusText);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	*/\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	function showHtml(data){	\r\n");
      out.write("		let html=\"<br>\";\r\n");
      out.write("		$.each(data, function(index,item){\r\n");
      out.write("			html +=\"<div class='article'>\";\r\n");
      out.write("			html +=\"<p>\"+item.title+\"</p>\";\r\n");
      out.write("			html +=\"<a href=''><img src='' alt='썸네일'>\";\r\n");
      out.write("			html +=\"<label><input type='checkbox' onclick='firstButton(id)'  id=\"+item.articleNum+\"-f>\";\r\n");
      out.write("			html +=\"<text>\"+item.ourSub+\"</text><label>\";\r\n");
      out.write("			html +=\"<label><input type='checkbox' onclick='secondButton(id)'  id=\"+item.articleNum+\"-s>\";			\r\n");
      out.write("			html +=\"<text>사이트 주인이 만든 글귀<button>댓글 더보기</button></text></label></div>\";					\r\n");
      out.write("		});	\r\n");
      out.write("		//document.querySelector(\".content\").innerHtml += html;	\r\n");
      out.write("		$(\".content\").html(html);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
