/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-02-25 02:33:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/ModuleProject/0223NEWNEW/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LastTest2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642730976753L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link href=\"/app/resources/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("/*	console.log(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("	window.onload = function (String){\r\n");
      out.write("		console.log(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"+\" in the fuc\");\r\n");
      out.write("		const id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		console.log(id);\r\n");
      out.write("		const mypage = document.querySelector(\".mp\");\r\n");
      out.write("		const loginpage = document.querySelector(\".lp\");\r\n");
      out.write("		const\r\n");
      out.write("		mypage.style.display = \"none\";\r\n");
      out.write("	if(id!=\"\"){\r\n");
      out.write("		mypage.style.display = 'none';\r\n");
      out.write("		loginpage.style.display = 'inline-block';\r\n");
      out.write("	}else {\r\n");
      out.write("		mypage.style.display = 'inline-block';\r\n");
      out.write("		loginpage.style.display = 'none';\r\n");
      out.write("	};\r\n");
      out.write("	};\r\n");
      out.write("	*/\r\n");
      out.write("</script>\r\n");
      out.write("<header class=\"head\" id=\"tops\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <h1><a href=\"./main\" target=\"_parent\">ㅇㅌㅊㅊ!</a></h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"search\">\r\n");
      out.write("        <select>\r\n");
      out.write("            <option>네이버</option>\r\n");
      out.write("            <option>탑툰</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <input type=\"text\" id=\"main_serach\" placeholder=\"제목을 입력해주세요\"> <button>검색하기</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"top_notifi\">\r\n");
      out.write("    <span><a href=\"./notification\" target=\"_parent\">공지사항</a>:사이트접속에 문제가 있는점 죄송합니다</span>\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("    <div class=\"login\">        \r\n");
      out.write("        <ul>\r\n");
      out.write("           <!--  <input type=\"checkbox\"value=\"로그인\" class=\"logged\"> -->\r\n");
      out.write("           	<li class=\"hello\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님 안녕하세요!<li>\r\n");
      out.write("            <li><a href=\"./mypage\" target=\"_parent\" class=\"mp\">마이페이지 |</a></li> <!-- .login > ul > li:nth-of-child(1) -->\r\n");
      out.write("            <li><a href=\"./login\" target=\"_parent\" class=\"lp\">로그인 |</a></li>\r\n");
      out.write("            <li><a href=\"./signin\" target=\"_parent\" class=\"sp\">회원가입 |</a></li>\r\n");
      out.write("            <li><a href=\"\" target=\"_parent\" class=\"logout\" onclick=\"logout()\">로그아웃</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("<menu>\r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"./top\" target=\"_parent\"> T O P </a></li>\r\n");
      out.write("            <li><a href=\"./today\" target=\"_parent\"> 오 늘 의  추 천 </a></li>\r\n");
      out.write("            <li><a href=\"./genre\" target=\"_parent\"> 장 르 </a></li>\r\n");
      out.write("            <li><a href=\"./bbs\" target=\"_parent\"> 자 유  게 시 판 </a></li>  \r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</menu>\r\n");
      out.write("\r\n");
      out.write("<hr>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
