/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-02-25 01:04:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <!--기본 틀-->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        div.relative {\r\n");
      out.write("  /* border: 3px solid #73AD21; */\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("div.absolute {\r\n");
      out.write("  display:none;\r\n");
      out.write("}\r\n");
      out.write("div.pop_close span {\r\n");
      out.write("	background:rgba(146, 163, 121, 0.315);\r\n");
      out.write("	color:white;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	width:250px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".score{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: flex-end;\r\n");
      out.write("    bottom: 200px;\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("<head>\r\n");
      out.write("    <link href=\"/app/resources/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/app/resources/images/thumb.png\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"들어오지 마셈\" />\r\n");
      out.write("    <meta property=\"og:description\" content=\"뭐보지? 하믄 들어와\" />\r\n");
      out.write("    <meta property=\"og:image\" content=\"/app/resources/images/thumb.png\" }\" />\r\n");
      out.write("    <title>ㅇㅌㅊㅊ</title>\r\n");
      out.write("   \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("	\r\n");
      out.write("    const buttonList = document.querySelectorAll('[type=button]');\r\n");
      out.write("    const popList = document.querySelectorAll('.pop_close span');\r\n");
      out.write("    \r\n");
      out.write("    buttonList.forEach((button) => {\r\n");
      out.write("        button.addEventListener('click',() => {\r\n");
      out.write("            const bid = button.getAttribute('id');\r\n");
      out.write("            const pclass = '#pop_'+bid;\r\n");
      out.write("            const popup = document.querySelector(pclass);\r\n");
      out.write("            popup.style.display = 'block';\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    popList.forEach((span) => {\r\n");
      out.write("        span.addEventListener('click',() => {\r\n");
      out.write("            const sid = span.getAttribute('id');\r\n");
      out.write("            const pclass = '#pop_'+sid;\r\n");
      out.write("            const popup = document.querySelector(pclass);\r\n");
      out.write("            popup.style.display = 'none';\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("    </script><!--\r\n");
      out.write("    <header class=\"head\" id=\"header\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <h1><a href=\"./main.html\">ㅇㅌㅊㅊ!</a></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search\">\r\n");
      out.write("            <select>\r\n");
      out.write("                <option>네이버</option>\r\n");
      out.write("                <option>탑툰</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\" id=\"main_serach\"> <button>검색하기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"login\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"./login.html\">로그인</a>></li>\r\n");
      out.write("                <li><a href=\"./signin.html\">회원가입</a>></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <menu>\r\n");
      out.write("        <div class=\"menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"./top.html\"> T O P </a></li>\r\n");
      out.write("                <li><a href=\"./today.html\"> 오 늘 의  추 천 </a></li>\r\n");
      out.write("                <li><a href=\"./genre.html\"> 장 르 </a></li>\r\n");
      out.write("                <li><a href=\"./bbs.html\"> 자 유  게 시 판 </a></li>    \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </menu>  -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <ul> <!--  -->\r\n");
      out.write("            <div class=\"isaid\">김성모가 박태준이랑 같이 연재를 했다? 이거 대작일지도..?</div>\r\n");
      out.write("            <li><div class=\"container\" id=\"n-124\">\r\n");
      out.write("                <img src=\"/app/resources/images/n-124.jpg\" class=\"tumb1\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783054&no=71\">최신화</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783054&no=70\">최신화-1</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783054&no=69\">최신화-2</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783054&no=1\">정주행</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/list?titleId=783054\">전체보기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"score\">\r\n");
      out.write("                <div class=\"relative\">\r\n");
      out.write("                    <button type=\"button\" id=\"n-783054-or\">ㅇㅌㅊㅊ! 점수</button>\r\n");
      out.write("                      <div class=\"absolute\" id=\"pop_n-783054-or\">\r\n");
      out.write("                        <div class=\"pop_close\"><span id=\"n-783054-or\">추천수 : 800<br>조회수 : 800</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"relative\">\r\n");
      out.write("                    <button type=\"button\" id=\"n-783054-tr\">해당 사이트 점수!</button>\r\n");
      out.write("                      <div class=\"absolute\" id=\"pop_n-783054-tr\">\r\n");
      out.write("                          <div class=\"pop_close\"><span id=\"n-783054-tr\">추천수 : 800<br>조회수 : 800</span></div>  \r\n");
      out.write("                      </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"our rating\"><button onclick=\"or(id)\" id=\"n-783052-or\">점수</button></div>\r\n");
      out.write("                <div class=\"they rating\"><button onclick=\"tr(id)\" id=\"n-783052-tr\">점수</button></div> -->\r\n");
      out.write("            </div></li>\r\n");
      out.write("            <div class=\"isaid\">미션을 깨면 카드를 준다? 심지어 훔쳐보기 까지!?</div>\r\n");
      out.write("            <li><div class=\"container\" id=\"n-783052\">\r\n");
      out.write("                <img src=\"/app/resources/images/n-783052.jpg\" class=\"tumb2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783052&no=18\">최신화</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783052&no=17\">최신화-1</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783052&no=16\">최신화-2</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/detail?titleId=783052&no=1\">정주행</a></li>\r\n");
      out.write("                    <li><a href=\"https://comic.naver.com/webtoon/list?titleId=783052\">전체보기</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"score\">\r\n");
      out.write("                <div class=\"relative\">\r\n");
      out.write("                    <button type=\"button\" id=\"n-783052-or\">ㅇㅌㅊㅊ! 점수</button>\r\n");
      out.write("                      <div class=\"absolute\" id=\"pop_n-783052-or\">\r\n");
      out.write("                        <div class=\"pop_close\"><span id=\"n-783052-or\">추천수 : 800<br>조회수 : 800</span></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"relative\">\r\n");
      out.write("                    <button type=\"button\" id=\"n-783052-tr\">해당 사이트 점수!</button>\r\n");
      out.write("                      <div class=\"absolute\" id=\"pop_n-783052-tr\">\r\n");
      out.write("                          <div class=\"pop_close\"><span id=\"n-783052-tr\">추천수 : 800<br>조회수 : 800</span></div>  \r\n");
      out.write("                      </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                <!-- <div class=\"our rating\"><button onclick=\"or(id)\" id=\"n-783052-or\">점수</button></div>\r\n");
      out.write("                <div class=\"they rating\"><button onclick=\"tr(id)\" id=\"n-783052-tr\">점수</button></div> -->\r\n");
      out.write("            </div></li>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </ul><!-- ../images/n-783052.jpg -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div></div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer.jsp", out, false);
      out.write("\r\n");
      out.write("   <!-- <footer> \r\n");
      out.write("        <hr>\r\n");
      out.write("        <div id=\"scroll\">\r\n");
      out.write("            <a href=\"#header\"><img src=\"../images/scroll.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer> -->\r\n");
      out.write("   <!--  <script>/*\r\n");
      out.write("        document.addEventListener('DOMttentLoaded', () => {\r\n");
      out.write("	\r\n");
      out.write("    const buttonList = document.querySelectorAll('[type=button]')\r\n");
      out.write("    const popList = document.querySelectorAll('.pop_close span')\r\n");
      out.write("    \r\n");
      out.write("    buttonList.forEach((button) => {\r\n");
      out.write("        button.addEventListener('click',() => {\r\n");
      out.write("            const bid = button.getAttribute('id')\r\n");
      out.write("            const pclass = '#pop_'+bid\r\n");
      out.write("            const popup = document.querySelector(pclass)\r\n");
      out.write("            popup.style.display = 'block'\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    popList.forEach((span) => {\r\n");
      out.write("        span.addEventListener('click',() => {\r\n");
      out.write("            const sid = span.getAttribute('id')\r\n");
      out.write("            const pclass = '#pop_'+sid\r\n");
      out.write("            const popup = document.querySelector(pclass)\r\n");
      out.write("            popup.style.display = 'none'\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("});*/\r\n");
      out.write("    </script>-->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
