/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-02-24 05:41:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .mypage{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row-reverse;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("        }\r\n");
      out.write("        .list {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            height: 600px;\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-family:  맑은 고딕;\r\n");
      out.write("        }\r\n");
      out.write("        .list span{\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .table{\r\n");
      out.write("            width: 600px;\r\n");
      out.write("        }\r\n");
      out.write("        .account span{\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-family:  맑은 고딕;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .account > div{\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            margin: 15px;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("            border: solid 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("    <link href=\"/app/resources/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/app/resources/images/thumb.png\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"/app/resources/images/thumb.png\" }\" />\r\n");
      out.write("    <meta property=\"og:description\" content=\"뭐보지? 하믄 들어와\" />\r\n");
      out.write("    <title>ㅇㅌㅊㅊ</title>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header.jsp", out, false);
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  <div class=\"mypage\">\r\n");
      out.write("      <div class=\"list\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <span>작성 글보기</span>\r\n");
      out.write("            <ol>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                     \r\n");
      out.write("                                <th>제목</th>\r\n");
      out.write("                                <th>날짜</th>\r\n");
      out.write("                                <th>조회수</th>\r\n");
      out.write("                                <th>추천수</th>\r\n");
      out.write(" \r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <hr>\r\n");
      out.write("                        <tbody class=\"bbs-list\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><a href=\"#\">나야나야</a></td>\r\n");
      out.write("                                <td>2021-02-23-13:13</td>\r\n");
      out.write("                                <td>450회</td>\r\n");
      out.write("                                <td>15회</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><a href=\"#\">나아니야</a></td>\r\n");
      out.write("                                <td>2021-02-23-13:13</td>\r\n");
      out.write("                                <td>500회</td>\r\n");
      out.write("                                <td>115회</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><a href=\"#\">너야너</a></td>\r\n");
      out.write("                                <td>2021-02-23-13:13</td>\r\n");
      out.write("                                <td>600회</td>\r\n");
      out.write("                                <td>1115회</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"account\">\r\n");
      out.write("          <div class=\"nickFix\">\r\n");
      out.write("              <span>닉네임</span>\r\n");
      out.write("              <form>\r\n");
      out.write("                  <input type=\"text\" placeholder=\"변경할 닉네임을 입력해주세요.\">\r\n");
      out.write("                  <button>수정</button>\r\n");
      out.write("              </form>\r\n");
      out.write("              \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"passFix\">\r\n");
      out.write("            <span>비밀번호 수정</span>\r\n");
      out.write("            <form>\r\n");
      out.write("                <input type=\"password\" placeholder=\"현재 비밀번호\">\r\n");
      out.write("                <input type=\"password\" placeholder=\"변경할 비밀번호\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("                <button>수정</button>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
